.TH clear 1 ""
.ds n 5
.SH NAME
\fBclear\fR - clear the terminal screen
.SH SYNOPSIS
\fBclear\fR
.br
.SH DESCRIPTION
\fBclear\fR clears your screen if this is possible.  It looks in the
environment for the terminal type and then in the \fBterminfo\fR database to
figure out how to clear the screen.
.SH SEE ALSO
\fBtput\fR(1), \fBterminfo\fR(\*n)
.\"#
.\"# The following sets edit modes for GNU EMACS
.\"# Local Variables:
.\"# mode:nroff
.\"# fill-column:79
.\"# End:
