ifeq ($(subdir),ncurses)

CPPFLAGS += -DNDEBUG -DHAVE_CONFIG_H

edit_man-sed = sysdeps/unix/sysv/linux/edit_man.sed
edit_man-sh = sysdeps/unix/sysv/linux/edit_man.sh

run_tic-sh = sysdeps/unix/sysv/linux/run_tic.sh

endif
